# Generated by Django 6.0 on 2025-12-27 12:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('detection_data', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('upload_type', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('detected_classes', models.TextField()),
                ('image_data', models.TextField(blank=True, null=True)),
                ('video_data', models.TextField(blank=True, null=True)),
                ('is_stored_in_db', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'detections',
            },
        ),
    ]
