# Generated by Django 6.0 on 2026-01-17 19:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=200)),
                ('detection_data', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('upload_type', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('detected_classes', models.JSONField(default=list)),
                ('image_data', models.ImageField(blank=True, null=True, upload_to='detections/images/')),
                ('video_data', models.FileField(blank=True, null=True, upload_to='detections/videos/')),
                ('is_stored_in_db', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'detections',
            },
        ),
    ]
