# Generated by Django 6.0 on 2025-12-31 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='image_data',
            field=models.ImageField(blank=True, null=True, upload_to='detections/images/'),
        ),
        migrations.AlterField(
            model_name='detection',
            name='video_data',
            field=models.FileField(blank=True, null=True, upload_to='detections/videos/'),
        ),
    ]
