# Generated by Django 6.0 on 2026-01-04 17:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_detection_image_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
