# Generated by Django 6.0 on 2026-01-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_detection_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='detected_classes',
            field=models.JSONField(default=list),
        ),
    ]
